#  ___ _ _
# / __(_) |_ ___
# \__ \ |  _/ -_)
# |___/_|\__\___|
# Basic settings
site:
  title: Green Code Initiative
  start_page: green-code-initiative::index.adoc

#   ___         _           _
#  / __|___ _ _| |_ ___ _ _| |_
# | (__/ _ \ ' \  _/ -_) ' \  _|
#  \___\___/_||_\__\___|_||_\__|
# Provides the content sources to generate the build
content:
  sources:
    - url: .
      start_path: docs
      # branches: main # Don't specify branch, build the current one
  edit_url: 'https://github.com/green-code-challenge-2025/green-code-initiative-docs/edit/{refname}/{path}'

#  _   _ ___
# | | | |_ _|
# | |_| || |
#  \___/|___|
# Defines the UI for the generated website
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

#    _       _
#   /_\  _ _| |_ ___ _ _ __ _
#  / _ \| ' \  _/ _ \ '_/ _` |
# /_/ \_\_||_\__\___/_| \__,_|
# Configures Antora further
antora:
  # Antora extensions can insert themselves in the build cycle to customize the build
  extensions:
    # Lunr-extension adds a search field based on JavaScript-based Lunr index
    - require: '@antora/lunr-extension'
