site:
  title: Green Code Initiative
  start_page: green-code-initiative::index.adoc

content:
  sources:
    - url: .
      start_path: docs
      # branches: main # Don't specify branch, build the current one
  # edit_url: '{web_url}/edit/{refname}/{path}'
  edit_url: 'https://github.com/green-code-challenge-2025/green-code-initiative-docs/edit/{refname}/{path}'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
