name: Publish to GitHub Pages
# TODO note about publishing on GH pages with a custom domain: https://docs.antora.org/antora/latest/publish-to-github-pages/#using-a-custom-domain
on:
  push:
    branches: [main, feature/deploy-on-gh-pages]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions: # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install NPM dependencies
        run: npm i
      - name: Generate Site
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
